### ISSUE TITLE
remove use of go-options

### ISSUE THREAD

**Issue by loganmeetsworld** [buzzfeed/sso#10]
**Is your feature request related to a problem? Please describe.**
We currently use go-options to allow us to either start sso-auth and sso-proxy via CLI or config file. Rather than having two different ways of starting these binaries, it seems like a good idea to stick to one way.

**Describe the solution you'd like**
* Run binaries using a config file.
   * Pro: More secure
    * Con: Will require more work.
* CLI Solution
   * Con: It is possible to leak sensitive secrets via CLI
   * Pro: Easier since we already use it.

**Comment by snebel29** [comment]
Have you considered using something like https://github.com/spf13/viper ? You could potentially remove some boilerplate code and provide flexibility for users on what to use for configuring `sso`, as well as providing overrides, etc. out of the box

Cheers

**Comment by shrayolacrayon** [comment]
We actually don't use go-options anymore, I think it just needs to be removed from the Godeps. We use `envconfig` to parse environment variables into the options configuration.

**Comment by snebel29** [comment]
Hi @shrayolacrayon 
Actually I wasn't referring to `go-options` specifically, but just suggesting the idea of using cobra/viper instead of `envconfig` and custom logic, to get config from either CLI, environment vars and/or config files all out-of-the-box.

I don't think that should be too difficult to implement but I just came to this repository and I barely know about it, I also think this would play well with other opened issues such as https://github.com/buzzfeed/sso/issues/34 and https://github.com/buzzfeed/sso/issues/36 but this is also a design decision that's on your side. :smile: 

I'm happy to POC and show ithen PR f there is and interest.

Cheers

**Comment by mreiferson** [comment]
See #10
