### ISSUE TITLE
A way to define allowed_emails in upstream-config

### ISSUE THREAD

**Issue by xeor** [buzzfeed/sso#161]
**Is your feature request related to a problem? Please describe.**
After https://github.com/buzzfeed/sso/pull/113 is done allowing the usage of allowed email addresses, it was not thought about to implement that in `upstream-config` as well.
Without that, the `allowed email adresses` option only allowing all those mail adresses to login, without a way to allow them based on the list of upstreams.

**Describe the solution you'd like**
Just like I can add `allowed_groups` in upstream-config, there should be an `allowed_emails` as well.

**Describe alternatives you've considered**
Alternative is to have multiple sso to be able to use fine grained control

**Additional context**
This is related to https://github.com/buzzfeed/sso/pull/113 (which fixed https://github.com/buzzfeed/sso/issues/32)

**Comment by victornoel** [comment]
I would add that a user either in a group of `allowed_groups` OR in `allowed_users` should be authorized if both are specified. I.e., only one of those suffice to grant access.

**Comment by Jusshersmith** [comment]
Hey @xeor, 

Thanks for submitting this! The ability to add allowed email addresses (and domains) into upstream configs, rather than just globally for all upstreams was added in https://github.com/buzzfeed/sso/pull/247. 

We'll also be adding some additional logic soon to allow access providing one of these 'validations' passes: https://github.com/buzzfeed/sso/pull/253 (cc @victornoel) 

Thanks again!
