### ISSUE TITLE
[K8s] (SSO_)EMAIL_ADDRESSES is ignored

### ISSUE THREAD

**Issue by StiviiK** [buzzfeed/sso#192]
**Describe the bug**
I've deployed buzzfeed-sso to my k8s cluster and configured it with the email-root domain `googlemail.com` but now i want to allow only certain mails on this domain.
To test the filter i allowed only a random mail, which is definitely not mine, but i still can login normal with my normal address.
Edit: I also tried changing the `GOOGLE_ADMIN_EMAIL` to something random so it doesn't match my mail.

Did i missconfigure something?

**Expected behavior**
I would expect that my login attempt / page hit gets blocked

**Screenshots**
![image](https://user-images.githubusercontent.com/8115642/57384166-5b369f80-71b0-11e9-9e7f-f7f7cf17e572.png)
![image](https://user-images.githubusercontent.com/8115642/57384168-5d006300-71b0-11e9-9cad-2ab3d021d1f0.png)

**Additional context**
Azure Kubernetes Service

**Comment by benjsto** [comment]
Thanks for the report @StiviiK - I've been looking into this and it appears the issue is just that the `sso-dev/latest` image hasn't been updated recently and doesn't have the changes necessary for this functionality. As a workaround you can pull a specific image release like `buzzfeed/sso:v1.2.0`. We'll sort out getting the `latest` tag updated as needed. Thanks again!

**Comment by benjsto** [comment]
See here for the `latest` tag issue: https://github.com/buzzfeed/sso/issues/193
