### ISSUE TITLE
"error redeeming authorization code" when using a self-generated AUTH_CODE_SECRET

### ISSUE THREAD

**Issue by shinkbr** [buzzfeed/sso#203]
**Describe the bug**
I am unable to get buzzfeed/sso to work using a self-generated AUTH_CODE_SECRET.

I'm trying to launch this based on quickstart/docker-compose.yml with some tweaks.
It seems to work just fine, except when I change the AUTH_CODE_SECRET value from the demo default to a value generated via `openssl rand -base64 32` , it raises an error `error redeeming authorization code`, `got 401 from \"https://<my-server>/redeem\" invalid auth code: siv: authentication failed`.

I tried AUTH_CODE_SECRETs generated via the following methods, as specified in various locations across this repository:
- `openssl rand -base64 32`
- `openssl rand -base64 32 | head -c 32 | base64`
- `openssl rand 32 | head -c 32 | base64`

**To Reproduce**
1. `git clone git@github.com:buzzfeed/sso.git`
2. `cd sso/quickstart`
3. change the values of AUTH_CODE_SECRET (for both sso-proxy and sso-auth) in docker-compose.yml to an output of `openssl rand -base64 32`
4. `docker-compose up`
5. using your browser, go through the `hello-world` authentication process
6. when the process is complete, the browser will display `Internal Error` `HTTP 500` and `error redeeming authorization code`, `got 401 from \"https://<my-server>/redeem\" invalid auth code: siv: authentication failed` will be logged.

**Expected behavior**
Contents of upstream server will be proxied, as with when using the demo default value of AUTH_CODE_SECRET.

**Question**
Could someone tell me the correct way to generate the AUTH_CODE_SECRET?

**Server (please complete the following information):**
 - OS: Ubuntu 18.04 on Amazon EC2

**Desktop (please complete the following information):**
 - OS: macOS 10.14.5
 - Browser: Chrome 74.0.3729.169 & Firefox 66.0.5

**Additional context**
Changing the value of COOKIE_SECRET to a value generated via `openssl rand -base64 32` works just fine. Therefore, I expected that AUTH_CODE_SECRET to work just as well.

**Comment by Jusshersmith** [comment]
Hi @shinkbr!

Apologies for the delay in getting back to you on this. I am however having trouble replicating this issue. 

While I investigate a little bit deeper, would you mind confirming that you’re still experiencing this (after  starting with a clean setup perhaps)? To confirm, the correct way to create these secrets _is_ via: `openssl rand 32 -base64`

Would you also mind clarifying what version of SSO you’re running please?

Thank you!

**Comment by shinkbr** [comment]
Hi @Jusshersmith,

Thanks for taking a look, and sorry for my belated response.

I haven't given a try for starting all over from a clean setup, but I am still experiencing this issue.

> Would you also mind clarifying what version of SSO you’re running please?

I am running v1.2.0 of the docker releases.

**Comment by shinkbr** [comment]
@Jusshersmith Another question related to this issue.
The demo uses a value of `SVM0NEFMUUlaZGxyaFVhOGxsQ0wvOFYyZTh2S2Fha1U=` as the `AUTH_CODE_SECRET`.
https://github.com/buzzfeed/sso/blob/master/quickstart/docker-compose.yml#L48

However, this doesn't seem to be a result of `openssl rand 32 -base64` . Instead, this seems to be a base64 of another base64 string of a 24 byte data.
```bash
# The original base64 string can be decoded into another base64 string,
$ echo -n 'SVM0NEFMUUlaZGxyaFVhOGxsQ0wvOFYyZTh2S2Fha1U=' | base64 -D
IS44ALQIZdlrhUa8llCL/8V2e8vKaakU

# which can be decoded into a 24 byte data.
$ echo -n 'IS44ALQIZdlrhUa8llCL/8V2e8vKaakU' | base64 -D | wc -c
      24
```

That said, are you sure these values are produced by `openssl rand 32 -base64` ?

**Comment by shinkbr** [comment]
@Jusshersmith Do `AUTH_CODE_SECRET`s have to be generated in a certain manner? (for example, fetched from OAuth provider, have to be the same between sso-auth and sso-proxy, have to use a certain seed, etc)

**Comment by Jusshersmith** [comment]
Hi @shinkbr - I'm really sorry for not getting back to you on these. I'll be taking some time on Monday to work through this again and properly answer your questions.

Thank you for your patience!

**Comment by Jusshersmith** [comment]
Hi @shinkbr

Since this issue was originally raised there's been a large number of changes, particularly to the configuration variable side of things. I'd suggest trying this on the newest version if possible (`2.0.0` - https://github.com/buzzfeed/sso/releases/tag/v2.0.0).

Around how `AUTH_CODE_SECRET` was originally created; from what I understand the original method to create that value was via `openssl rand -base64 32 | head -c 32 | base64`. The documentation was at some point simplified to suggest the use of `openssl rand -base64 32` instead. I don't think the value in the quickstart was updated to match (likely because both worked). I think that might be where some of this confusion has arisen, and so should be updated on our end.

The correct/suggested way to create that value though _is_ `openssl rand -base64 32` (please note, this variable has changed slightly in `2.0.0`, though I believe the method remains the same).

I've also tested this value where it was created using LibreSSL 2.6.5, on macOS mojave and found it to work as expected. Would you mind also giving me an example of an `AUTH_CODE_SECRET` value you've tried to use please?

Would moving onto SSO `2.0.0` be feasible for you at this point? I think that might be best way forward -- it would be interesting to see if you still run into similar issues then.

**Comment by shinkbr** [comment]
@Jusshersmith Thanks for the response. As you mentioned, updating to the latest version, 2.0.0 has fixed this problem, and now I'm able to get sso up and runnig as expected.

> Would you mind also giving me an example of an AUTH_CODE_SECRET value you've tried to use please?

Below are some examples of what I've tried (if you are still interested)
- `ypfOWocUglq+lwFquXOCLnWp/h54P28AJejub/5HS+s=` (`openssl rand -base64 32`)
- `QSs4TWVGVUFSR3o4ZHdyNXh3RWRPVGZRblptVXFLQmU=` (`openssl rand -base64 24 | head -c 32 | base64`)

Anyway, thanks for taking your time to check in on this issue!
