### ISSUE TITLE
Make provider http client timeout configurable

### ISSUE THREAD

**Issue by cameronattard** [buzzfeed/sso#241]
**Is your feature request related to a problem? Please describe.**
When the `allowed_groups` list is long, fetching Google groups seems to time out, causing `auth` to return a `503`.

**Describe the solution you'd like**
Make the timeout configurable.

**Additional context**
Relevant log line:
```
{"action":"profile","http_status":503,"level":"info","msg":"","proxy_host":"","remote_address":"100.96.89.16:59924","request_duration":5000.219029,"request_method":"GET","request_uri":"/google/profile?client_id=XXX%3D\u0026email=me%example.com\u0026groups=group1%40example.com%2Cproduct-group2%40example.com%2Cgroup3%40example.com%2Cgroup4%40example.com%2Cgroup5%40example.com%2Cgroup6%40example.com%2Cgroup7%40example.com%2Cgroup8%40example.com%2Cgroup9%40example.com%2Cgroup10%40example.com","service":"sso-authenticator","time":"2019-08-09 04:18:22.600","user":"","user_agent":"sso_proxy/HEAD"}
```

**Comment by cameronattard** [comment]
Closing this - my issues were resolved by https://github.com/buzzfeed/sso/issues/238#issuecomment-520534358.

**Comment by antonipp** [comment]
How did you manage to solve it? I am having the same problem but my `PROVIDER_*_GROUPCACHE_INTERVAL_REFRESH` is already properly set, as described in the solution for https://github.com/buzzfeed/sso/issues/238.

I have 16 Google groups and am consistently getting `503` errors with `request_duration` of 5 seconds for every 1st user request happening after re-deploying the SSO auth service.

I think that in order to solve the problem, we need to adjust this timeout here:
https://github.com/buzzfeed/sso/blob/5904bbfa0101c205cafae04c60703e7322b84988/internal/auth/providers/http_client.go#L10 (haven't tried recompiling and testing though)
