### ISSUE TITLE
How to set up without docker?

### ISSUE THREAD

**Issue by lakshaytalkstocomputer** [buzzfeed/sso#287]

**Comment by Jusshersmith** [comment]
Hi @lakshaytalkstocomputer,

SSO isn't fundamentally tied to Docker (individual binaries are included in each release), however we don't currently have any documentation to support using SSO with it. 

This issue was created to add some supporting documentation, however I'm afraid there's not been any progress yet as far as I'm aware: https://github.com/buzzfeed/sso/issues/81

**Comment by Jusshersmith** [comment]
I'm going to close this in favour of https://github.com/buzzfeed/sso/issues/81 -- please react/respond there if you have any additional thoughts (the inclusion of that link here will at least cause a reference to _this_ issue in the original one)
