### ISSUE TITLE
sso-proxy: refresh on error page leads to different error

### ISSUE THREAD

**Issue by hans-d** [buzzfeed/sso#94]
**Describe the bug**
Use an upstream where you try to login and get a "Group membership required" error. On refresh, this turns into "http: named cookie not present"

**Expected behavior**
The group membership required error should remain.

**Desktop (please complete the following information):**
Using docker image sso:latest (first - and so far only - release)
Applies to all OS/browsers

**Additional context**
Notice how the page url still has an `oauth2/callback?code=<code>` section.

**Comment by shrayolacrayon** [comment]
Thanks for opening @hans-d, this behavior exists because when there is a group membership error, the cookie session is cleared, which means that all session information does not exist, including the user email. 

To fix this, we could *not* clear the cookie which would then re-check for groups membership and display the appropriate error.  For context, the clearing session cookie logic is [here](https://github.com/buzzfeed/sso/blob/master/internal/proxy/oauthproxy.go#L958).

**Comment by hans-d** [comment]
The proposed fix should be good I think. Would allow for a shout to the google admin to fix something and let the user retry.

**Comment by Jusshersmith** [comment]
Thanks for raising this @hans-d! Fixed in https://github.com/buzzfeed/sso/pull/170.
